//! Conformance against the Lean model.
//!
//! `lean/vectors.txt` is generated by `lake exe vectors` from the same
//! definitions the theorems in `lean/WsSpec` are proved about. Every line is a
//! decision of the model; this test checks the Rust implementation makes the
//! identical decision, tying the proved specification to the shipped code.

use std::path::Path;

use ws::config::pick;
use ws::provider::Provider;
use ws::validate;

fn opt(token: &str) -> Option<&str> {
    (token != "-").then_some(token)
}

const fn verdict(ok: bool) -> &'static str {
    if ok { "ok" } else { "err" }
}

#[test]
fn rust_agrees_with_the_lean_model_on_every_vector() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("lean")
        .join("vectors.txt");
    let text = std::fs::read_to_string(&path).unwrap();
    let mut counts = [0_usize; 5];

    for line in text
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
    {
        let (input, expected) = line
            .split_once(" => ")
            .unwrap_or_else(|| panic!("bad line: {line}"));
        let fields: Vec<&str> = input.split(' ').collect();
        let actual = match fields.as_slice() {
            ["provider", flag, env, file] => {
                counts[0] += 1;
                let parse = |t: &str| opt(t).map(|name| name.parse::<Provider>().unwrap());
                pick(parse(flag), parse(env), parse(file), Provider::default())
                    .0
                    .to_string()
            }
            ["gateway", flag, env, file] => {
                counts[1] += 1;
                pick(
                    opt(flag),
                    opt(env),
                    opt(file),
                    ws::config::DEFAULT_GATEWAY_ID,
                )
                .0
                .to_owned()
            }
            ["limit", n] => {
                counts[2] += 1;
                verdict(validate::limit(n.parse().unwrap()).is_ok()).to_owned()
            }
            ["query_len", n] => {
                counts[3] += 1;
                let query = "q".repeat(n.parse().unwrap());
                verdict(validate::query(&query).is_ok()).to_owned()
            }
            ["parse", name] => {
                counts[4] += 1;
                // The model parses exact names; Rust additionally ignores ASCII
                // case, so only exact-case inputs appear in the vectors.
                name.parse::<Provider>()
                    .map_or_else(|_| "err".to_owned(), |p| p.to_string())
            }
            _ => panic!("unknown vector: {line}"),
        };
        assert_eq!(
            actual, expected,
            "disagreement with the Lean model on: {line}"
        );
    }

    // 4^3 provider layers, 2^3 gateway layers, limits 0..=20, 6 length boundaries, 6 names.
    assert_eq!(counts, [64, 8, 21, 6, 6], "vector file is incomplete");
}
