import WsSpec

/-!
Emits the decision table of the model as `vectors.txt`. The Rust test
`tests/lean_vectors.rs` replays every line against the implementation, so the
code that ships is checked against the definitions the theorems are about.
-/

open WsSpec

def optName : Option Provider → String
  | some p => p.name
  | none => "-"

def optStr : Option String → String
  | some s => s
  | none => "-"

def verdict (b : Bool) : String := if b then "ok" else "err"

def layers : List (Option Provider) := none :: Provider.all.map some

def providerVectors : List String := Id.run do
  let mut out := []
  for flag in layers do
    for env in layers do
      for file in layers do
        let r := (resolve flag env file Provider.default).1
        out := s!"provider {optName flag} {optName env} {optName file} => {r.name}" :: out
  return out.reverse

def gatewayVectors : List String := Id.run do
  let mut out := []
  for flag in [none, some "flag-gw"] do
    for env in [none, some "env-gw"] do
      for file in [none, some "file-gw"] do
        let r := (resolve flag env file "default").1
        out := s!"gateway {optStr flag} {optStr env} {optStr file} => {r}" :: out
  return out.reverse

def limitVectors : List String :=
  (List.range 21).map fun n => s!"limit {n} => {verdict (limitValid n)}"

def queryVectors : List String :=
  [0, 1, 2, 1023, 1024, 1025].map fun n => s!"query_len {n} => {verdict (queryLenValid n)}"

def parseVectors : List String :=
  ["ceramic", "exa", "linkup", "google", "ceramicx", "ex"].map fun s =>
    let r := match Provider.parse s with
      | some p => p.name
      | none => "err"
    s!"parse {s} => {r}"

def main : IO Unit := do
  IO.println "# Generated by `lake exe vectors` from lean/WsSpec. Do not edit; run `mise run proof:vectors`."
  for line in providerVectors ++ gatewayVectors ++ limitVectors ++ queryVectors ++ parseVectors do
    IO.println line
