import WsSpec

/-!
Emits the decision table of the model as `vectors.txt`. The Rust test
`tests/lean_vectors.rs` replays every line against the implementation, so the
code that ships is checked against the definitions the theorems are about.
-/

open WsSpec

def optName : Option Provider → String
  | some p => p.name
  | none => "-"

def optStr : Option String → String
  | some s => s
  | none => "-"

def verdict (b : Bool) : String := if b then "ok" else "err"

def layers : List (Option Provider) := none :: Provider.all.map some

def providerVectors : List String := Id.run do
  let mut out := []
  for flag in layers do
    for env in layers do
      for file in layers do
        let r := (resolve flag env file Provider.default).1
        out := s!"provider {optName flag} {optName env} {optName file} => {r.name}" :: out
  return out.reverse

def gatewayVectors : List String := Id.run do
  let mut out := []
  for flag in [none, some "flag-gw"] do
    for env in [none, some "env-gw"] do
      for file in [none, some "file-gw"] do
        let r := (resolve flag env file "default").1
        out := s!"gateway {optStr flag} {optStr env} {optStr file} => {r}" :: out
  return out.reverse

def limitVectors : List String :=
  (List.range 21).map fun n => s!"limit {n} => {verdict (limitValid n)}"

def queryVectors : List String :=
  [0, 1, 2, 1023, 1024, 1025].map fun n => s!"query_len {n} => {verdict (queryLenValid n)}"

def parseVectors : List String :=
  ["ceramic", "exa", "linkup", "google", "ceramicx", "ex"].map fun s =>
    let r := match Provider.parse s with
      | some p => p.name
      | none => "err"
    s!"parse {s} => {r}"

def urlVectors : List String :=
  [ "https://example.com", "http://example.com/a?b=c#d", "HTTPS://Example.com/",
    "hTtP://127.0.0.1:8080/x", "https://[::1]/", "http://user@example.com/",
    "", "example.com", "ftp://example.com", "file:///etc/passwd", "javascript:alert(1)",
    "data:text/html,hi", "http://", "https://", "https:///path", "http://?q", "http://#f",
    "http://:80", "http://@host", "http:example.com", "//example.com", "httpx://example.com",
    "https:/example.com" ].map fun s =>
    s!"url {if s.isEmpty then "-" else s} => {verdict (urlValid s)}"

def urlLenVectors : List String :=
  [19, 20, 2047, 2048, 2049, 4096].map fun n =>
    let s := "https://example.com/" ++ String.ofList (List.replicate (n - 20) 'a')
    s!"url_len {n} => {verdict (urlValid s)}"

def ipv4Vectors : List String :=
  [ (0,0,0,0), (0,1,2,3), (1,1,1,1), (8,8,8,8), (9,255,255,255), (10,0,0,1), (11,0,0,1),
    (100,63,255,255), (100,64,0,1), (100,127,255,255), (100,128,0,0), (126,255,255,255),
    (127,0,0,1), (127,255,255,255), (128,0,0,1), (169,253,0,1), (169,254,169,254),
    (169,255,0,1), (172,15,255,255), (172,16,0,1), (172,31,255,255), (172,32,0,0),
    (192,0,0,1), (192,0,1,1), (192,167,1,1), (192,168,1,1), (192,169,1,1), (198,17,0,1),
    (198,18,0,1), (198,19,255,255), (198,20,0,1), (223,255,255,255), (224,0,0,1),
    (240,0,0,1), (255,255,255,255) ].map fun (a, b, c, d) =>
    s!"ipv4 {a}.{b}.{c}.{d} => {verdict (ipv4Public a b c d)}"

def mimeVectors : List String :=
  [ "text/html", "application/xhtml+xml", "text/markdown", "text/x-markdown", "text/plain",
    "text/csv", "application/json", "application/xml", "application/javascript",
    "application/ld+json", "application/rss+xml", "application/pdf", "image/png",
    "image/svg+xml", "application/octet-stream", "text", "html", "application/jsonx" ].map
    fun s =>
      let r := match kindOf s with
        | some k => k.name
        | none => "err"
      s!"mime {s} => {r}"

def main : IO Unit := do
  IO.println "# Generated by `lake exe vectors` from lean/WsSpec. Do not edit; run `mise run proof:vectors`."
  for line in providerVectors ++ gatewayVectors ++ limitVectors ++ queryVectors ++ parseVectors
      ++ urlVectors ++ urlLenVectors ++ ipv4Vectors ++ mimeVectors do
    IO.println line
